// Code generated by https://github.com/rnben/gen-const-str DO NOT EDIT

// code const code comment msg
package code

// noErrorMsg if code is not found, GetMsg will return this
const noErrorMsg = "unknown error"

// messages get msg from const comment
var messages = map[int]string{

	ErrParams: "参数错误",
	ErrServer: "系统内部错误",
}

// GetMsg get error msg
func GetMsg(code int) string {
	msg, ok := messages[code]
	if !ok {
		return noErrorMsg
	}

	return msg
}
